### ISSUE TITLE
prompt()

### ISSUE THREAD

**Issue by xenophilios** [mdn/beginner-html-site-scripted#37]
### What information was incorrect, unhelpful, or incomplete?

The function setUserName() calls itself if the user enters nothing or an empty string.
If the user next enters a non-empty string, myName will be whatever was entered on the previous try, namely null or the empty string.
This problem can be avoided by repeating the prompt command, rather than calling the whole function again, but it would be nice to have an explanation of what is causing it.

### What did you expect to see?

x

**Comment by caugner** [comment]
Hi @xenophilios, 👋 

Thank you for reporting this. I had a look at the following code that you're probably referring to:

https://github.com/mdn/beginner-html-site-scripted/blob/39e48a8b901f04097a7e77757b13ff5543d7777a/scripts/main.js#L19-L27

To try it, I pasted the following in the console: 

```js
 function setUserName() { 
   let myName = window.prompt('Please enter your name.'); 
   if(!myName) { 
     setUserName(); 
   } else { 
     console.log({ myName });
   } 
 } 

setUserName();
```

First I provided an empty value and then a non-empty value, and the log output showed the non-empty value as expected.

Since the example seems to work as expected, I will go ahead and close this issue.

Please don't hesitate to leave a comment if I have missed anything. 🙏

**Comment by xenophilios** [comment]
I figured out what was going on, but it has been so long since I wrote my post that I can't remember the details.
